services:
    postgresql:
        container_name: postgresql-server
        image: postgres:16.8-bullseye

        networks:
          - mired
        #ports:
        #  - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - PGDATA=/var/lib/postgresql/data
        volumes:
          - ./data:/var/lib/postgresql/data
        restart: always
        labels:
          - "traefik.enable=true"
          - "traefik.tcp.routers.postresql.rule=HostSNI(`*`)"
          - "traefik.tcp.routers.postgresql.entrypoints=postgresql"
          - "traefik.tcp.services.postgresql.loadbalancer.server.port=5432"

networks:
    mired:
        external: true